// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportAssoWebApp.Models;

#nullable disable

namespace SportAssoWebApp.Migrations.SportAssoDb
{
    [DbContext(typeof(SportAssoContext))]
    partial class SportAssoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportAssoWebApp.Models.Adherent", b =>
                {
                    b.Property<int>("AdherentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdherentId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsEncadrant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("AdherentId")
                        .HasName("PK__Adherent__97189F0106640CDF");

                    b.HasIndex(new[] { "Email" }, "UQ__Adherent__A9D105348B178F61")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Adherents");
                });

            modelBuilder.Entity("SportAssoWebApp.Models.Creneau", b =>
                {
                    b.Property<int>("CreneauId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreneauId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DocumentsRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Hour")
                        .HasColumnType("time");

                    b.Property<string>("Lieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PlacesMax")
                        .HasColumnType("int");

                    b.Property<int?>("PlacesRestantes")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("CreneauId")
                        .HasName("PK__Creneaux__17AA69153C83E3FF");

                    b.HasIndex("SectionId");

                    b.ToTable("Creneaux", (string)null);
                });

            modelBuilder.Entity("SportAssoWebApp.Models.Inscription", b =>
                {
                    b.Property<int>("InscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InscriptionId"));

                    b.Property<int?>("AdherentId")
                        .HasColumnType("int");

                    b.Property<int?>("CreneauId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentsSubmitted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPaid")
                        .HasColumnType("bit");

                    b.HasKey("InscriptionId")
                        .HasName("PK__Inscript__3332B6760C79B1B0");

                    b.HasIndex("AdherentId");

                    b.HasIndex("CreneauId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("SportAssoWebApp.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<string>("SectionName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SectionId")
                        .HasName("PK__Sections__80EF08720DDDCA53");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("SportAssoWebApp.Models.Creneau", b =>
                {
                    b.HasOne("SportAssoWebApp.Models.Section", "Section")
                        .WithMany("Creneaux")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK__Creneaux__Sectio__3D5E1FD2");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SportAssoWebApp.Models.Inscription", b =>
                {
                    b.HasOne("SportAssoWebApp.Models.Adherent", "Adherent")
                        .WithMany("Inscriptions")
                        .HasForeignKey("AdherentId")
                        .HasConstraintName("FK__Inscripti__Adher__403A8C7D");

                    b.HasOne("SportAssoWebApp.Models.Creneau", "Creneau")
                        .WithMany("Inscriptions")
                        .HasForeignKey("CreneauId")
                        .HasConstraintName("FK__Inscripti__Crene__412EB0B6");

                    b.Navigation("Adherent");

                    b.Navigation("Creneau");
                });

            modelBuilder.Entity("SportAssoWebApp.Models.Adherent", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("SportAssoWebApp.Models.Creneau", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("SportAssoWebApp.Models.Section", b =>
                {
                    b.Navigation("Creneaux");
                });
#pragma warning restore 612, 618
        }
    }
}
